version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      next:
        patterns:
          - "next"
          - "next-seo"
          - "eslint-config-next"
      stylelint:
        patterns:
          - "stylelint"
          - "stylelint-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
