compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  stylelint-config-sass-guidelines@*:
    dependencies:
      postcss: "*"
  stylelint@*:
    dependencies:
      postcss-scss: "*"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
